# SwiftLint Configuration for LaserGRBL macOS

# Paths to include/exclude
included:
  - LaserGRBL-macOS

excluded:
  - Pods
  - LaserGRBL-macOS/LaserGRBL/LaserGRBL.xcodeproj
  - LaserGRBL

# Enabled rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional

# Disabled rules
disabled_rules:
  - trailing_whitespace # Can be noisy

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - x
    - y
    - z
    - id
    - i
    - j
    - k

# Severity customization
force_cast: warning
force_try: warning

# Reporter type
reporter: "xcode"

