; Generated by LaserGRBL for macOS
; Date: 10/10/2025, 9:40 AM
; File: square
G21 ; Set units to millimeters
G90 ; Absolute positioning
M5 ; Laser off
G0 X0 Y0 ; Move to origin

G21 ; Set units to millimeters
G90 ; Absolute positioning
M5 ; Laser off
G0 X0 Y0 F3000
M3 S500
G1 X50 Y0 F100
G1 X50 Y50
G1 X0 Y50
G1 X0 Y0
M5
G0 X0 Y0

; Program end
M5 ; Laser off
G0 X0 Y0 ; Return to origin
